//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograV.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Proyecto_PrograVEntities1 : DbContext
    {
        public Proyecto_PrograVEntities1()
            : base("name=Proyecto_PrograVEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<BitacoraErrores> BitacoraErrores { get; set; }
        public virtual DbSet<BitacoraTransacciones> BitacoraTransacciones { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<documento_identidad> documento_identidad { get; set; }
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<prestamo> prestamo { get; set; }
        public virtual DbSet<prestamo_libro> prestamo_libro { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual int ObtenerTodosLosUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ObtenerTodosLosUsuarios");
        }
    
        public virtual int RegistrarBitacoraErrores(string descripcionError, Nullable<System.DateTime> momentoError, string usuario)
        {
            var descripcionErrorParameter = descripcionError != null ?
                new ObjectParameter("DescripcionError", descripcionError) :
                new ObjectParameter("DescripcionError", typeof(string));
    
            var momentoErrorParameter = momentoError.HasValue ?
                new ObjectParameter("MomentoError", momentoError) :
                new ObjectParameter("MomentoError", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarBitacoraErrores", descripcionErrorParameter, momentoErrorParameter, usuarioParameter);
        }
    
        public virtual int sp_actualizar_autor(Nullable<int> p_autor_id, Nullable<int> p_persona_id, string p_identificacion, string p_nombre, string p_apellido1, string p_apellido2, Nullable<System.DateTime> p_fecha_nacimiento, Nullable<System.DateTime> p_fecha_defuncion, ObjectParameter p_respuesta)
        {
            var p_autor_idParameter = p_autor_id.HasValue ?
                new ObjectParameter("p_autor_id", p_autor_id) :
                new ObjectParameter("p_autor_id", typeof(int));
    
            var p_persona_idParameter = p_persona_id.HasValue ?
                new ObjectParameter("p_persona_id", p_persona_id) :
                new ObjectParameter("p_persona_id", typeof(int));
    
            var p_identificacionParameter = p_identificacion != null ?
                new ObjectParameter("p_identificacion", p_identificacion) :
                new ObjectParameter("p_identificacion", typeof(string));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_apellido1Parameter = p_apellido1 != null ?
                new ObjectParameter("p_apellido1", p_apellido1) :
                new ObjectParameter("p_apellido1", typeof(string));
    
            var p_apellido2Parameter = p_apellido2 != null ?
                new ObjectParameter("p_apellido2", p_apellido2) :
                new ObjectParameter("p_apellido2", typeof(string));
    
            var p_fecha_nacimientoParameter = p_fecha_nacimiento.HasValue ?
                new ObjectParameter("p_fecha_nacimiento", p_fecha_nacimiento) :
                new ObjectParameter("p_fecha_nacimiento", typeof(System.DateTime));
    
            var p_fecha_defuncionParameter = p_fecha_defuncion.HasValue ?
                new ObjectParameter("p_fecha_defuncion", p_fecha_defuncion) :
                new ObjectParameter("p_fecha_defuncion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_autor", p_autor_idParameter, p_persona_idParameter, p_identificacionParameter, p_nombreParameter, p_apellido1Parameter, p_apellido2Parameter, p_fecha_nacimientoParameter, p_fecha_defuncionParameter, p_respuesta);
        }
    
        public virtual int sp_actualizar_categoria(Nullable<int> p_categoria_id, string p_nombre, ObjectParameter p_respuesta)
        {
            var p_categoria_idParameter = p_categoria_id.HasValue ?
                new ObjectParameter("p_categoria_id", p_categoria_id) :
                new ObjectParameter("p_categoria_id", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_categoria", p_categoria_idParameter, p_nombreParameter, p_respuesta);
        }
    
        public virtual int sp_actualizar_documento_identidad(Nullable<int> p_documento_identidad_id, string p_nombre, ObjectParameter p_respuesta)
        {
            var p_documento_identidad_idParameter = p_documento_identidad_id.HasValue ?
                new ObjectParameter("p_documento_identidad_id", p_documento_identidad_id) :
                new ObjectParameter("p_documento_identidad_id", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_documento_identidad", p_documento_identidad_idParameter, p_nombreParameter, p_respuesta);
        }
    
        public virtual int sp_actualizar_libro(Nullable<int> p_libro_id, string p_titulo, Nullable<System.DateTime> p_fecha_publicacion, Nullable<int> p_categoria_id, Nullable<int> p_autor_id, Nullable<int> p_unidades_disponibles, string p_estado, string p_descripcion, ObjectParameter p_respuesta)
        {
            var p_libro_idParameter = p_libro_id.HasValue ?
                new ObjectParameter("p_libro_id", p_libro_id) :
                new ObjectParameter("p_libro_id", typeof(int));
    
            var p_tituloParameter = p_titulo != null ?
                new ObjectParameter("p_titulo", p_titulo) :
                new ObjectParameter("p_titulo", typeof(string));
    
            var p_fecha_publicacionParameter = p_fecha_publicacion.HasValue ?
                new ObjectParameter("p_fecha_publicacion", p_fecha_publicacion) :
                new ObjectParameter("p_fecha_publicacion", typeof(System.DateTime));
    
            var p_categoria_idParameter = p_categoria_id.HasValue ?
                new ObjectParameter("p_categoria_id", p_categoria_id) :
                new ObjectParameter("p_categoria_id", typeof(int));
    
            var p_autor_idParameter = p_autor_id.HasValue ?
                new ObjectParameter("p_autor_id", p_autor_id) :
                new ObjectParameter("p_autor_id", typeof(int));
    
            var p_unidades_disponiblesParameter = p_unidades_disponibles.HasValue ?
                new ObjectParameter("p_unidades_disponibles", p_unidades_disponibles) :
                new ObjectParameter("p_unidades_disponibles", typeof(int));
    
            var p_estadoParameter = p_estado != null ?
                new ObjectParameter("p_estado", p_estado) :
                new ObjectParameter("p_estado", typeof(string));
    
            var p_descripcionParameter = p_descripcion != null ?
                new ObjectParameter("p_descripcion", p_descripcion) :
                new ObjectParameter("p_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_libro", p_libro_idParameter, p_tituloParameter, p_fecha_publicacionParameter, p_categoria_idParameter, p_autor_idParameter, p_unidades_disponiblesParameter, p_estadoParameter, p_descripcionParameter, p_respuesta);
        }
    
        public virtual int sp_actualizar_persona(Nullable<int> p_persona_id, string p_identificacion, string p_nombre, string p_apellido1, string p_apellido2, Nullable<System.DateTime> p_fecha_nacimiento)
        {
            var p_persona_idParameter = p_persona_id.HasValue ?
                new ObjectParameter("p_persona_id", p_persona_id) :
                new ObjectParameter("p_persona_id", typeof(int));
    
            var p_identificacionParameter = p_identificacion != null ?
                new ObjectParameter("p_identificacion", p_identificacion) :
                new ObjectParameter("p_identificacion", typeof(string));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_apellido1Parameter = p_apellido1 != null ?
                new ObjectParameter("p_apellido1", p_apellido1) :
                new ObjectParameter("p_apellido1", typeof(string));
    
            var p_apellido2Parameter = p_apellido2 != null ?
                new ObjectParameter("p_apellido2", p_apellido2) :
                new ObjectParameter("p_apellido2", typeof(string));
    
            var p_fecha_nacimientoParameter = p_fecha_nacimiento.HasValue ?
                new ObjectParameter("p_fecha_nacimiento", p_fecha_nacimiento) :
                new ObjectParameter("p_fecha_nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_persona", p_persona_idParameter, p_identificacionParameter, p_nombreParameter, p_apellido1Parameter, p_apellido2Parameter, p_fecha_nacimientoParameter);
        }
    
        public virtual int sp_actualizar_prestamo(Nullable<int> p_prestamo_id, Nullable<System.DateTime> p_fecha_prestamo, Nullable<System.DateTime> p_fecha_devolucion, string p_detalle, Nullable<int> p_usuario_id, string p_estado, string p_libros, ObjectParameter p_respuesta)
        {
            var p_prestamo_idParameter = p_prestamo_id.HasValue ?
                new ObjectParameter("p_prestamo_id", p_prestamo_id) :
                new ObjectParameter("p_prestamo_id", typeof(int));
    
            var p_fecha_prestamoParameter = p_fecha_prestamo.HasValue ?
                new ObjectParameter("p_fecha_prestamo", p_fecha_prestamo) :
                new ObjectParameter("p_fecha_prestamo", typeof(System.DateTime));
    
            var p_fecha_devolucionParameter = p_fecha_devolucion.HasValue ?
                new ObjectParameter("p_fecha_devolucion", p_fecha_devolucion) :
                new ObjectParameter("p_fecha_devolucion", typeof(System.DateTime));
    
            var p_detalleParameter = p_detalle != null ?
                new ObjectParameter("p_detalle", p_detalle) :
                new ObjectParameter("p_detalle", typeof(string));
    
            var p_usuario_idParameter = p_usuario_id.HasValue ?
                new ObjectParameter("p_usuario_id", p_usuario_id) :
                new ObjectParameter("p_usuario_id", typeof(int));
    
            var p_estadoParameter = p_estado != null ?
                new ObjectParameter("p_estado", p_estado) :
                new ObjectParameter("p_estado", typeof(string));
    
            var p_librosParameter = p_libros != null ?
                new ObjectParameter("p_libros", p_libros) :
                new ObjectParameter("p_libros", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_prestamo", p_prestamo_idParameter, p_fecha_prestamoParameter, p_fecha_devolucionParameter, p_detalleParameter, p_usuario_idParameter, p_estadoParameter, p_librosParameter, p_respuesta);
        }
    
        public virtual int sp_actualizar_rol(Nullable<int> p_rol_id, string p_nombre, ObjectParameter p_respuesta)
        {
            var p_rol_idParameter = p_rol_id.HasValue ?
                new ObjectParameter("p_rol_id", p_rol_id) :
                new ObjectParameter("p_rol_id", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_rol", p_rol_idParameter, p_nombreParameter, p_respuesta);
        }
    
        public virtual int sp_actualizar_usuario(Nullable<int> p_usuario_id, Nullable<int> p_rol_id, Nullable<int> p_persona_id, Nullable<int> p_documento_identidad_id, string p_email, string p_contrasena, Nullable<bool> p_estado, string p_identificacion, string p_nombre, string p_apellido1, string p_apellido2, Nullable<System.DateTime> p_fecha_nacimiento, ObjectParameter p_respuesta)
        {
            var p_usuario_idParameter = p_usuario_id.HasValue ?
                new ObjectParameter("p_usuario_id", p_usuario_id) :
                new ObjectParameter("p_usuario_id", typeof(int));
    
            var p_rol_idParameter = p_rol_id.HasValue ?
                new ObjectParameter("p_rol_id", p_rol_id) :
                new ObjectParameter("p_rol_id", typeof(int));
    
            var p_persona_idParameter = p_persona_id.HasValue ?
                new ObjectParameter("p_persona_id", p_persona_id) :
                new ObjectParameter("p_persona_id", typeof(int));
    
            var p_documento_identidad_idParameter = p_documento_identidad_id.HasValue ?
                new ObjectParameter("p_documento_identidad_id", p_documento_identidad_id) :
                new ObjectParameter("p_documento_identidad_id", typeof(int));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_contrasenaParameter = p_contrasena != null ?
                new ObjectParameter("p_contrasena", p_contrasena) :
                new ObjectParameter("p_contrasena", typeof(string));
    
            var p_estadoParameter = p_estado.HasValue ?
                new ObjectParameter("p_estado", p_estado) :
                new ObjectParameter("p_estado", typeof(bool));
    
            var p_identificacionParameter = p_identificacion != null ?
                new ObjectParameter("p_identificacion", p_identificacion) :
                new ObjectParameter("p_identificacion", typeof(string));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_apellido1Parameter = p_apellido1 != null ?
                new ObjectParameter("p_apellido1", p_apellido1) :
                new ObjectParameter("p_apellido1", typeof(string));
    
            var p_apellido2Parameter = p_apellido2 != null ?
                new ObjectParameter("p_apellido2", p_apellido2) :
                new ObjectParameter("p_apellido2", typeof(string));
    
            var p_fecha_nacimientoParameter = p_fecha_nacimiento.HasValue ?
                new ObjectParameter("p_fecha_nacimiento", p_fecha_nacimiento) :
                new ObjectParameter("p_fecha_nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_usuario", p_usuario_idParameter, p_rol_idParameter, p_persona_idParameter, p_documento_identidad_idParameter, p_emailParameter, p_contrasenaParameter, p_estadoParameter, p_identificacionParameter, p_nombreParameter, p_apellido1Parameter, p_apellido2Parameter, p_fecha_nacimientoParameter, p_respuesta);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_consultar_autor_Result> sp_consultar_autor(Nullable<int> p_autor_id)
        {
            var p_autor_idParameter = p_autor_id.HasValue ?
                new ObjectParameter("p_autor_id", p_autor_id) :
                new ObjectParameter("p_autor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_autor_Result>("sp_consultar_autor", p_autor_idParameter);
        }
    
        public virtual ObjectResult<sp_consultar_categoria_Result> sp_consultar_categoria(Nullable<int> p_categoria_id)
        {
            var p_categoria_idParameter = p_categoria_id.HasValue ?
                new ObjectParameter("p_categoria_id", p_categoria_id) :
                new ObjectParameter("p_categoria_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_categoria_Result>("sp_consultar_categoria", p_categoria_idParameter);
        }
    
        public virtual ObjectResult<sp_consultar_documento_identidad_Result> sp_consultar_documento_identidad(Nullable<int> p_documento_identidad_id)
        {
            var p_documento_identidad_idParameter = p_documento_identidad_id.HasValue ?
                new ObjectParameter("p_documento_identidad_id", p_documento_identidad_id) :
                new ObjectParameter("p_documento_identidad_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_documento_identidad_Result>("sp_consultar_documento_identidad", p_documento_identidad_idParameter);
        }
    
        public virtual ObjectResult<sp_consultar_libro_Result> sp_consultar_libro(Nullable<int> p_libro_id)
        {
            var p_libro_idParameter = p_libro_id.HasValue ?
                new ObjectParameter("p_libro_id", p_libro_id) :
                new ObjectParameter("p_libro_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_libro_Result>("sp_consultar_libro", p_libro_idParameter);
        }
    
        public virtual ObjectResult<sp_consultar_persona_Result> sp_consultar_persona(Nullable<int> p_persona_id)
        {
            var p_persona_idParameter = p_persona_id.HasValue ?
                new ObjectParameter("p_persona_id", p_persona_id) :
                new ObjectParameter("p_persona_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_persona_Result>("sp_consultar_persona", p_persona_idParameter);
        }
    
        public virtual ObjectResult<sp_consultar_prestamo_Result> sp_consultar_prestamo(Nullable<int> p_prestamo_id)
        {
            var p_prestamo_idParameter = p_prestamo_id.HasValue ?
                new ObjectParameter("p_prestamo_id", p_prestamo_id) :
                new ObjectParameter("p_prestamo_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_prestamo_Result>("sp_consultar_prestamo", p_prestamo_idParameter);
        }
    
        public virtual ObjectResult<sp_consultar_rol_Result> sp_consultar_rol(Nullable<int> p_rol_id)
        {
            var p_rol_idParameter = p_rol_id.HasValue ?
                new ObjectParameter("p_rol_id", p_rol_id) :
                new ObjectParameter("p_rol_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_rol_Result>("sp_consultar_rol", p_rol_idParameter);
        }
    
        public virtual ObjectResult<sp_consultar_usuario_Result> sp_consultar_usuario(Nullable<int> p_usuario_id)
        {
            var p_usuario_idParameter = p_usuario_id.HasValue ?
                new ObjectParameter("p_usuario_id", p_usuario_id) :
                new ObjectParameter("p_usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_usuario_Result>("sp_consultar_usuario", p_usuario_idParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarBitacoraTransacciones_Result> sp_ConsultarBitacoraTransacciones(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarBitacoraTransacciones_Result>("sp_ConsultarBitacoraTransacciones", usuarioParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_guardar_autor(Nullable<int> p_persona_id, string p_identificacion, string p_nombre, string p_apellido1, string p_apellido2, Nullable<System.DateTime> p_fecha_nacimiento, Nullable<System.DateTime> p_fecha_defuncion, ObjectParameter p_respuesta)
        {
            var p_persona_idParameter = p_persona_id.HasValue ?
                new ObjectParameter("p_persona_id", p_persona_id) :
                new ObjectParameter("p_persona_id", typeof(int));
    
            var p_identificacionParameter = p_identificacion != null ?
                new ObjectParameter("p_identificacion", p_identificacion) :
                new ObjectParameter("p_identificacion", typeof(string));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_apellido1Parameter = p_apellido1 != null ?
                new ObjectParameter("p_apellido1", p_apellido1) :
                new ObjectParameter("p_apellido1", typeof(string));
    
            var p_apellido2Parameter = p_apellido2 != null ?
                new ObjectParameter("p_apellido2", p_apellido2) :
                new ObjectParameter("p_apellido2", typeof(string));
    
            var p_fecha_nacimientoParameter = p_fecha_nacimiento.HasValue ?
                new ObjectParameter("p_fecha_nacimiento", p_fecha_nacimiento) :
                new ObjectParameter("p_fecha_nacimiento", typeof(System.DateTime));
    
            var p_fecha_defuncionParameter = p_fecha_defuncion.HasValue ?
                new ObjectParameter("p_fecha_defuncion", p_fecha_defuncion) :
                new ObjectParameter("p_fecha_defuncion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_autor", p_persona_idParameter, p_identificacionParameter, p_nombreParameter, p_apellido1Parameter, p_apellido2Parameter, p_fecha_nacimientoParameter, p_fecha_defuncionParameter, p_respuesta);
        }
    
        public virtual int sp_guardar_categoria(string p_nombre, ObjectParameter p_respuesta)
        {
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_categoria", p_nombreParameter, p_respuesta);
        }
    
        public virtual int sp_guardar_documento_identidad(string p_nombre, ObjectParameter p_respuesta)
        {
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_documento_identidad", p_nombreParameter, p_respuesta);
        }
    
        public virtual int sp_guardar_libro(string p_titulo, Nullable<System.DateTime> p_fecha_publicacion, Nullable<int> p_categoria_id, Nullable<int> p_autor_id, Nullable<int> p_unidades_disponibles, string p_estado, string p_descripcion, ObjectParameter p_respuesta)
        {
            var p_tituloParameter = p_titulo != null ?
                new ObjectParameter("p_titulo", p_titulo) :
                new ObjectParameter("p_titulo", typeof(string));
    
            var p_fecha_publicacionParameter = p_fecha_publicacion.HasValue ?
                new ObjectParameter("p_fecha_publicacion", p_fecha_publicacion) :
                new ObjectParameter("p_fecha_publicacion", typeof(System.DateTime));
    
            var p_categoria_idParameter = p_categoria_id.HasValue ?
                new ObjectParameter("p_categoria_id", p_categoria_id) :
                new ObjectParameter("p_categoria_id", typeof(int));
    
            var p_autor_idParameter = p_autor_id.HasValue ?
                new ObjectParameter("p_autor_id", p_autor_id) :
                new ObjectParameter("p_autor_id", typeof(int));
    
            var p_unidades_disponiblesParameter = p_unidades_disponibles.HasValue ?
                new ObjectParameter("p_unidades_disponibles", p_unidades_disponibles) :
                new ObjectParameter("p_unidades_disponibles", typeof(int));
    
            var p_estadoParameter = p_estado != null ?
                new ObjectParameter("p_estado", p_estado) :
                new ObjectParameter("p_estado", typeof(string));
    
            var p_descripcionParameter = p_descripcion != null ?
                new ObjectParameter("p_descripcion", p_descripcion) :
                new ObjectParameter("p_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_libro", p_tituloParameter, p_fecha_publicacionParameter, p_categoria_idParameter, p_autor_idParameter, p_unidades_disponiblesParameter, p_estadoParameter, p_descripcionParameter, p_respuesta);
        }
    
        public virtual int sp_guardar_persona(string p_identificacion, string p_nombre, string p_apellido1, string p_apellido2, Nullable<System.DateTime> p_fecha_nacimiento, ObjectParameter p_respuesta)
        {
            var p_identificacionParameter = p_identificacion != null ?
                new ObjectParameter("p_identificacion", p_identificacion) :
                new ObjectParameter("p_identificacion", typeof(string));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_apellido1Parameter = p_apellido1 != null ?
                new ObjectParameter("p_apellido1", p_apellido1) :
                new ObjectParameter("p_apellido1", typeof(string));
    
            var p_apellido2Parameter = p_apellido2 != null ?
                new ObjectParameter("p_apellido2", p_apellido2) :
                new ObjectParameter("p_apellido2", typeof(string));
    
            var p_fecha_nacimientoParameter = p_fecha_nacimiento.HasValue ?
                new ObjectParameter("p_fecha_nacimiento", p_fecha_nacimiento) :
                new ObjectParameter("p_fecha_nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_persona", p_identificacionParameter, p_nombreParameter, p_apellido1Parameter, p_apellido2Parameter, p_fecha_nacimientoParameter, p_respuesta);
        }
    
        public virtual int sp_guardar_prestamo(Nullable<System.DateTime> p_fecha_prestamo, Nullable<System.DateTime> p_fecha_devolucion, string p_detalle, Nullable<int> p_usuario_id, string p_estado, string p_libros, ObjectParameter p_respuesta)
        {
            var p_fecha_prestamoParameter = p_fecha_prestamo.HasValue ?
                new ObjectParameter("p_fecha_prestamo", p_fecha_prestamo) :
                new ObjectParameter("p_fecha_prestamo", typeof(System.DateTime));
    
            var p_fecha_devolucionParameter = p_fecha_devolucion.HasValue ?
                new ObjectParameter("p_fecha_devolucion", p_fecha_devolucion) :
                new ObjectParameter("p_fecha_devolucion", typeof(System.DateTime));
    
            var p_detalleParameter = p_detalle != null ?
                new ObjectParameter("p_detalle", p_detalle) :
                new ObjectParameter("p_detalle", typeof(string));
    
            var p_usuario_idParameter = p_usuario_id.HasValue ?
                new ObjectParameter("p_usuario_id", p_usuario_id) :
                new ObjectParameter("p_usuario_id", typeof(int));
    
            var p_estadoParameter = p_estado != null ?
                new ObjectParameter("p_estado", p_estado) :
                new ObjectParameter("p_estado", typeof(string));
    
            var p_librosParameter = p_libros != null ?
                new ObjectParameter("p_libros", p_libros) :
                new ObjectParameter("p_libros", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_prestamo", p_fecha_prestamoParameter, p_fecha_devolucionParameter, p_detalleParameter, p_usuario_idParameter, p_estadoParameter, p_librosParameter, p_respuesta);
        }
    
        public virtual int sp_guardar_rol(string p_nombre, ObjectParameter p_respuesta)
        {
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_rol", p_nombreParameter, p_respuesta);
        }
    
        public virtual int sp_guardar_usuario(Nullable<int> p_rol_id, Nullable<int> p_persona_id, Nullable<int> p_documento_identidad_id, string p_email, string p_contrasena, Nullable<bool> p_estado, string p_identificacion, string p_nombre, string p_apellido1, string p_apellido2, Nullable<System.DateTime> p_fecha_nacimiento, ObjectParameter p_respuesta)
        {
            var p_rol_idParameter = p_rol_id.HasValue ?
                new ObjectParameter("p_rol_id", p_rol_id) :
                new ObjectParameter("p_rol_id", typeof(int));
    
            var p_persona_idParameter = p_persona_id.HasValue ?
                new ObjectParameter("p_persona_id", p_persona_id) :
                new ObjectParameter("p_persona_id", typeof(int));
    
            var p_documento_identidad_idParameter = p_documento_identidad_id.HasValue ?
                new ObjectParameter("p_documento_identidad_id", p_documento_identidad_id) :
                new ObjectParameter("p_documento_identidad_id", typeof(int));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_contrasenaParameter = p_contrasena != null ?
                new ObjectParameter("p_contrasena", p_contrasena) :
                new ObjectParameter("p_contrasena", typeof(string));
    
            var p_estadoParameter = p_estado.HasValue ?
                new ObjectParameter("p_estado", p_estado) :
                new ObjectParameter("p_estado", typeof(bool));
    
            var p_identificacionParameter = p_identificacion != null ?
                new ObjectParameter("p_identificacion", p_identificacion) :
                new ObjectParameter("p_identificacion", typeof(string));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_apellido1Parameter = p_apellido1 != null ?
                new ObjectParameter("p_apellido1", p_apellido1) :
                new ObjectParameter("p_apellido1", typeof(string));
    
            var p_apellido2Parameter = p_apellido2 != null ?
                new ObjectParameter("p_apellido2", p_apellido2) :
                new ObjectParameter("p_apellido2", typeof(string));
    
            var p_fecha_nacimientoParameter = p_fecha_nacimiento.HasValue ?
                new ObjectParameter("p_fecha_nacimiento", p_fecha_nacimiento) :
                new ObjectParameter("p_fecha_nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guardar_usuario", p_rol_idParameter, p_persona_idParameter, p_documento_identidad_idParameter, p_emailParameter, p_contrasenaParameter, p_estadoParameter, p_identificacionParameter, p_nombreParameter, p_apellido1Parameter, p_apellido2Parameter, p_fecha_nacimientoParameter, p_respuesta);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_listar_autor_Result> sp_listar_autor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_autor_Result>("sp_listar_autor");
        }
    
        public virtual ObjectResult<sp_listar_categoria_Result> sp_listar_categoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_categoria_Result>("sp_listar_categoria");
        }
    
        public virtual ObjectResult<sp_listar_documento_identidad_Result> sp_listar_documento_identidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_documento_identidad_Result>("sp_listar_documento_identidad");
        }
    
        public virtual ObjectResult<sp_listar_libro_Result> sp_listar_libro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_libro_Result>("sp_listar_libro");
        }
    
        public virtual ObjectResult<sp_listar_persona_Result> sp_listar_persona()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_persona_Result>("sp_listar_persona");
        }
    
        public virtual ObjectResult<sp_listar_prestamo_Result> sp_listar_prestamo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_prestamo_Result>("sp_listar_prestamo");
        }
    
        public virtual ObjectResult<sp_listar_prestamo_libro_Result> sp_listar_prestamo_libro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_prestamo_libro_Result>("sp_listar_prestamo_libro");
        }
    
        public virtual ObjectResult<sp_listar_rol_Result> sp_listar_rol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_rol_Result>("sp_listar_rol");
        }
    
        public virtual ObjectResult<sp_listar_usuario_Result> sp_listar_usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_usuario_Result>("sp_listar_usuario");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_ValidarUsuario_Result> SP_ValidarUsuario(string email, string contrasena)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ValidarUsuario_Result>("SP_ValidarUsuario", emailParameter, contrasenaParameter);
        }
    }
}
