//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograV.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libro()
        {
            this.prestamo_libro = new HashSet<prestamo_libro>();
        }
    
        public int libro_id { get; set; }
        public string titulo { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
        public int categoria_id { get; set; }
        public int autor_id { get; set; }
        public int unidades_disponibles { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
    
        public virtual autor autor { get; set; }
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo_libro> prestamo_libro { get; set; }
    }
}
