//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograV.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prestamo()
        {
            this.prestamo_libro = new HashSet<prestamo_libro>();
        }
    
        public int prestamo_id { get; set; }
        public System.DateTime fecha_prestamo { get; set; }
        public System.DateTime fecha_devolucion { get; set; }
        public string detalle { get; set; }
        public int usuario_id { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo_libro> prestamo_libro { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
