//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograV.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo_libro
    {
        public int prestamo_libro_id { get; set; }
        public int libro_id { get; set; }
        public int prestamo_id { get; set; }
    
        public virtual libro libro { get; set; }
        public virtual prestamo prestamo { get; set; }
    }
}
