//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograV.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int usuario_id { get; set; }
        public int rol_id { get; set; }
        public int persona_id { get; set; }
        public int documento_identidad_id { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public string estado { get; set; }
    
        public virtual documento_identidad documento_identidad { get; set; }
        public virtual persona persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
        public virtual rol rol { get; set; }
    }
}
